### ISSUE TITLE
wow theres a discord webhook in it

### ISSUE THREAD

**Issue by master7720** [Kiriyaga7615/banana-plus-crack#1]

**Comment by Kiriyaga7615** [comment]
only hwid check was changed 🥶

**Comment by master7720** [comment]
i know i wasnt saying you added it in there

**Comment by jewish5959** [comment]
bitcoin miner🥶🥶🥶

**Comment by EurekaEffect** [comment]
> i know i wasnt saying you added it in there

it just sends info which player is loaded, user or no

**Comment by CEONOS** [comment]
didn't eurekaeeffect rat a b+ leak? I wouldn't take his word on anything, or use this. Not even gunna look in the source. these leaks are never clean.

**Comment by EurekaEffect** [comment]
its clean bruh

ср, 8 дек. 2021 г., 16:22 CEONOS ***@***.***>:

**Comment by CEONOS** [comment]
ill waste some time. if it is ill let everyone know. if it isnt. I am a Forensic tools enjoyer and will run it.

**Comment by EurekaEffect** [comment]
ok hero

ср, 8 дек. 2021 г., 16:26 CEONOS ***@***.***>:

**Comment by EurekaEffect** [comment]
original jar was from banana+ release channel

ср, 8 дек. 2021 г., 16:27 CEONOS ***@***.***>:

**Comment by CEONOS** [comment]
ill eat my words it is clean

**Comment by Terrio123** [comment]
> didn't eurekaeeffect rat a b+ leak? I wouldn't take his word on anything, or use this. Not even gunna look in the source. these leaks are never clean.

I looked through the src and didnt see anything fishy. do u think this 0.0.8 b+ leak is a rat?

**Comment by EurekaEffect** [comment]
🤡

пн, 13 дек. 2021 г., 17:33 Terrio123 ***@***.***>:

**Comment by CEONOS** [comment]
This one is fine but already to outdated to bother with.

**Comment by Kiriyaga7615** [comment]
nothing important to changed from 2 month outdated version, so i don't think it's important

**Comment by cmk-Destro** [comment]
theres 2 webhook's
one its for the devs (to have the logs)
and another that "someone " added....
obs: DONT RUN IT

**Comment by EurekaEffect** [comment]
> theres 2 webhook's one its for the devs (to have the logs) and another that "someone " added.... obs: DONT RUN IT

are you retarded? we did not add any webhook, while there is obf on banana +, we cannot add tokenlog there if we wanted to

**Comment by cmk-Destro** [comment]
u mad bro?

**Comment by EurekaEffect** [comment]
> u mad bro?

u dumb bro

**Comment by cmk-Destro** [comment]
you know what if u are that good at stealing and leaking private clients (and them rat them)
leak:
venomhack
meteor+
gl

**Comment by cmk-Destro** [comment]
and btw if u want prof:
[https://cdn.discordapp.com/attachments/870275971020886027/924336290097401886/unknown.png](url)

**Comment by EurekaEffect** [comment]
> and btw if u want prof:
> 
> https://cdn.discordapp.com/attachments/870275971020886027/924336290097401886/unknown.png

thats not prof lol, he just lying to u
ok, i'll post banana src cause of you

**Comment by cmk-Destro** [comment]
do it

**Comment by cmk-Destro** [comment]
ill wait

**Comment by cmk-Destro** [comment]
ez bluff 4 hours and still nothing kek

**Comment by EurekaEffect** [comment]
> ez bluff 4 hours and still nothing kek

https://cdn.discordapp.com/attachments/834495397983551538/924397891773169674/unknown.png

**Comment by EurekaEffect** [comment]
> ez bluff 4 hours and still nothing kek

I want to ask you why I should try to do something faster and thereby prove to some cmk-Destro

**Comment by cmk-Destro** [comment]
hahhaha sure buddyi have it aswl then lmao thats not the 0.0.80 ver lmao

**Comment by cmk-Destro** [comment]
this it mf https://github.com/ItsNautilus/banana-plus-0.0.44-hacked-client-leak

**Comment by EurekaEffect** [comment]
> hahhaha sure buddy anyone has it aswl then lmao thats not the 0.0.80 ver lmao

nah lol

**Comment by cmk-Destro** [comment]
if thats not fake fk post it 
u dont lose anything unless want ppl launch the jar..........

**Comment by EurekaEffect** [comment]
> 

i like how u keeps crying, compare my ss and https://github.com/ItsNautilus/banana-plus-0.0.44-hacked-client-leak/tree/master/bananaplusdevelopment/addons/modules

**Comment by cmk-Destro** [comment]
make it pub then
if not it only proves my point

**Comment by EurekaEffect** [comment]
> make it pub then if not it only proves my point

im doing it rn BRUH

**Comment by cmk-Destro** [comment]
kek
ima wait 4h again for a ss

**Comment by EurekaEffect** [comment]
> kek ima wait 4h again for a ss

https://github.com/EurekaEffect/banana-plus-crack

**Comment by cmk-Destro** [comment]
wow u did it congrats lmao

**Comment by forota123** [comment]
Wow there is a webhook wtf

**Comment by Notme11** [comment]
sheeeeesshh

**Comment by Kiriyaga7615** [comment]
> you know what if u are that good at stealing and leaking private clients (and them rat them) leak: venomhack meteor+ gl



webhook was added to main class, i tested is b+ log sender is a rat. i deleted that webhook so it's looks like http/discordwebhook/nothingHereLol

you need to test any information by yourself before starting coping(anyway you will cope cuz you losted 8$ to vanilla auto jump with cracks for all versions)
